on: pull_request

name: Pull Requests

jobs:
  message-check:
    name: Block Merge Commits

    runs-on: ubuntu-latest

    steps:
      - name: Block Merge Commits
        uses: Morishiri/block-merge-commits-action@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
