# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Issue bot"

on:
  pull_request:
    paths-ignore:
      - 'compiler/**'
      - 'apigen/**'
      - 'changelog-generator/**'
  push:
    branches:
      - "1.9.x"
    paths-ignore:
      - 'compiler/**'
      - 'apigen/**'
      - 'changelog-generator/**'

concurrency:
  group: tests-${{ github.head_ref || github.run_id }} # will be canceled on subsequent pushes in pull requests but not branches
  cancel-in-progress: true

jobs:
  download:
    name: "Download data"

    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout"
        uses: actions/checkout@v3

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.1"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Install Issue Bot dependencies"
        working-directory: "issue-bot"
        run: "composer install --no-interaction --no-progress"

      - name: "Cache downloads"
        uses: actions/cache@v3
        with:
          path: ./issue-bot/tmp
          key: "issue-bot-download-v2-${{ github.run_id }}"
          restore-keys: |
            issue-bot-download-v2-

      - name: "Download data"
        working-directory: "issue-bot"
        env:
          GITHUB_PAT: ${{ secrets.PHPSTAN_BOT_TOKEN }}
        run: ./console.php download
