# https://help.github.com/en/categories/automating-your-workflow-with-github-actions
name: Merge PHP 8 stubs update

on:
  check_suite:
    types:
      - completed

jobs:
  merge:
    name: Merge PHP 8 stubs update
    runs-on: ubuntu-latest
    steps:
      - name: Merge
        if: ${{ github.event.workflow_run.conclusion == 'success' }}
        uses: ridedott/merge-me-action@v2
        with:
          GITHUB_LOGIN: phpstan-bot
          GITHUB_TOKEN: ${{ secrets.PHPSTAN_BOT_TOKEN }}
          MERGE_METHOD: REBASE
