# https://help.github.com/en/categories/automating-your-workflow-with-github-actions

name: "Compile PHAR"

on:
  push:
    branches:
      - "1.5.x"
    tags:
      - '1.5.*'

concurrency: phar

jobs:
  compile:
    name: "Compile PHAR"
    runs-on: "ubuntu-latest"
    timeout-minutes: 60

    steps:
      - name: "Checkout"
        uses: "actions/checkout@v2"
        with:
          fetch-depth: 0

      - name: "Install PHP"
        uses: "shivammathur/setup-php@v2"
        with:
          coverage: "none"
          php-version: "8.0"

      - name: "Install dependencies"
        run: "composer install --no-interaction --no-progress"

      - name: "Install compiler dependencies"
        run: "composer install --no-interaction --no-progress --working-dir=compiler"

      - name: "Compile PHAR"
        run: php compiler/bin/compile

      - name: "Configure GPG signing key"
        run: echo "$GPG_SIGNING_KEY" | base64 --decode | gpg --import --no-tty --batch --yes
        env:
          GPG_SIGNING_KEY: ${{ secrets.GPG_SIGNING_KEY }}

      - name: "Get Git log"
        id: git-log
        run: echo ::set-output name=log::$(git log ${{ github.event.before }}..${{ github.event.after }} --reverse --pretty='%H %s' | sed -e 's/^/https:\/\/github.com\/phpstan\/phpstan-src\/commit\//')

      - name: "Checkout phpstan-dist"
        uses: "actions/checkout@v2"
        with:
          repository: phpstan/phpstan
          path: phpstan-dist
          token: ${{ secrets.PAT }}
          ref: 1.5.x

      - name: "cp PHAR"
        run: cp tmp/phpstan.phar phpstan-dist/phpstan.phar

      - name: "Sign PHAR"
        working-directory: phpstan-dist
        run: rm phpstan.phar.asc && gpg --command-fd 0 --pinentry-mode loopback -u "$GPG_ID" --batch --detach-sign --armor --output phpstan.phar.asc phpstan.phar
        env:
          GPG_ID: ${{ secrets.GPG_ID }}

      - name: "Verify PHAR"
        working-directory: phpstan-dist
        run: "gpg --verify phpstan.phar.asc"

      - name: "Set Git signing key"
        working-directory: phpstan-dist
        run: git config user.signingkey "$GPG_ID"
        env:
          GPG_ID: ${{ secrets.GPG_ID }}

      - name: "Commit PHAR - development"
        if: "!startsWith(github.ref, 'refs/tags/')"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "Ondrej Mirtes"
          commit_user_email: "ondrej@mirtes.cz"
          commit_author: "Ondrej Mirtes <ondrej@mirtes.cz>"
          commit_options: "--gpg-sign"
          repository: phpstan-dist
          commit_message: "Updated PHPStan to commit ${{ github.event.after }}\n\n${{ steps.git-log.outputs.log }}"

      - name: "Commit PHAR - tag"
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_user_name: "Ondrej Mirtes"
          commit_user_email: "ondrej@mirtes.cz"
          commit_author: "Ondrej Mirtes <ondrej@mirtes.cz>"
          commit_options: "--gpg-sign"
          repository: phpstan-dist
          commit_message: "PHPStan ${{github.ref_name}}\n\n${{ steps.git-log.outputs.log }}"
          tagging_message: ${{github.ref_name}}
